(function(){
	var typeJson={
		"player":{
			"speed":20,
			"imageName":"player",
			"width":12,
			"height":55
			
		},
		"小圆1":{
			"pandingXing":"圆",
			"speed":5,
			"imageName":"bullet1",
			"width":12,
			"height":12,
			"px":82,
			"py":242,
			"pandingR":5
		},
		"长椭1":{
			"pandingXing":"方",
			"speed":3,
			"imageName":"bullet2",
			"width":14,
			"height":30,
			"px":10,
			"py":129,
			"pandingW":8,
			"pandingH":16
		},
		"小米1":{
			"pandingXing":"方",
			"speed":1,
			"imageName":"bullet1",
			"width":8,
			"height":16,
			"px":20,
			"py":128,
			"pandingW":6,
			"pandingH":10
		},
		"小小圆1":{
			"pandingXing":"圆",
			"speed":1,
			"imageName":"bullet1",
			"width":6,
			"height":8,
			"px":73,
			"py":192,
			"pandingR":4,
			
		},
		"红星大":{
			"pandingXing":"圆",
			"speed":2,
			"imageName":"etama6",
			"width":32,
			"height":32,
			"px":32,
			"py":0,
			"pandingR":8,
			"jiaodu":0,
			"djiaodu":0.05
		},
		"蓝星大":{
			"pandingXing":"圆",
			"speed":2,
			"imageName":"etama6",
			"width":32,
			"height":32,
			"px":96,
			"py":0,
			"pandingR":8,
			"jiaodu":0,
			"djiaodu":-0.05
		},
		"绿星大":{
			"pandingXing":"圆",
			"speed":2,
			"imageName":"etama6",
			"width":32,
			"height":32,
			"px":160,
			"py":0,
			"pandingR":8,
			"jiaodu":0,
			"djiaodu":0.05
		},
		"黄星大":{
			"pandingXing":"圆",
			"speed":2,
			"imageName":"etama6",
			"width":32,
			"height":32,
			"px":192,
			"py":0,
			"pandingR":8,
			"jiaodu":0,
			"djiaodu":-0.05
		},
		"紫星大":{
			"pandingXing":"圆",
			"speed":2,
			"imageName":"etama6",
			"width":32,
			"height":32,
			"px":64,
			"py":0,
			"pandingR":8,
			"jiaodu":0,
			"djiaodu":0.05
		},
		"绿星小":{
			"pandingXing":"圆",
			"speed":1,
			"imageName":"etama6",
			"width":16,
			"height":16,
			"px":160,
			"py":33,
			"pandingR":4,
			"jiaodu":0,
			"djiaodu":-0.05
		},
		"黄星小":{
			"pandingXing":"圆",
			"speed":1,
			"imageName":"etama6",
			"width":16,
			"height":16,
			"px":208,
			"py":33,
			"pandingR":4,
			"jiaodu":0,
			"djiaodu":0.05
		},
		"蓝星小":{
			"pandingXing":"圆",
			"speed":1,
			"imageName":"etama6",
			"width":16,
			"height":16,
			"px":128,
			"py":33,
			"pandingR":4,
			"jiaodu":0,
			"djiaodu":-0.05
		},
		"紫星小":{
			"pandingXing":"圆",
			"speed":1,
			"imageName":"etama6",
			"width":16,
			"height":16,
			"px":64,
			"py":33,
			"pandingR":4,
			"jiaodu":0,
			"djiaodu":0.05
		},
		"红星小":{
			"pandingXing":"圆",
			"speed":1,
			"imageName":"etama6",
			"width":16,
			"height":16,
			"px":32,
			"py":33,
			"pandingR":4,
			"jiaodu":0,
			"djiaodu":-0.05
		},
		"魔理沙的小激光红":{
			"pandingXing":"方",
			"speed":0,
			"imageName":"bullet1",
			"width":16,
			"height":14,
			"px":32,
			"py":1,
			"pandingW":16,
			"panddingH":300
		},
		"魔理沙的小激光黄":{
			"pandingXing":"方",
			"speed":0,
			"imageName":"bullet1",
			"width":16,
			"height":14,
			"px":208,
			"py":1,
			"pandingW":16,
			"panddingH":300
		},
		"魔理沙的小激光绿":{
			"pandingXing":"方",
			"speed":0,
			"imageName":"bullet1",
			"width":16,
			"height":14,
			"px":160,
			"py":1,
			"pandingW":16,
			"panddingH":300
		},
		"魔理沙的小激光蓝":{
			"pandingXing":"方",
			"speed":0,
			"imageName":"bullet1",
			"width":16,
			"height":14,
			"px":128,
			"py":1,
			"pandingW":16,
			"panddingH":300
		},
		"魔理沙的小激光紫":{
			"pandingXing":"方",
			"speed":0,
			"imageName":"bullet1",
			"width":16,
			"height":14,
			"px":64,
			"py":1,
			"pandingW":16,
			"panddingH":500
		},


	};
	var Bullet=window.Bullet=function(x,y,direction,type){
		this.x=x;
		this.y=y;
		this.type=type;
		this.direction=direction;//弧度
		this.speed=/*game.nanDu**/typeJson[this.type].speed;

		if(this.type == "红星大" || this.type == "蓝星大"|| this.type == "绿星大"|| this.type == "黄星大"|| this.type == "紫星大"||this.type == "绿星小" ||this.type == "黄星小" ||this.type=="蓝星小"||this.type=="紫星小"||this.type=="红星小"){
			this.jiaodu=typeJson[this.type].jiaodu;
			this.djiaodu=typeJson[this.type].djiaodu;
		}
		if(this.type =="魔理沙的小激光红"||this.type =="魔理沙的小激光黄" ||this.type =="魔理沙的小激光绿" ||this.type =="魔理沙的小激光蓝" ||this.type =="魔理沙的小激光紫"  ){
			this.rx=arguments[4];
			this.ry=arguments[5];
			this.r=arguments[6];
			this.dj=arguments[7];
			this.startDirection=this.direction;

		}
		if(this.type=="player"){

			game.playerBullets.push(this);
		}else{
			game.enemyBullets.push(this);
		}
	};
	Bullet.prototype.render=function(){
		if(this.type=="player"){
			game.ctx2.save();
			game.ctx2.translate(this.x-6,this.y);
			game.ctx2.rotate(-90*Math.PI/180);
			game.ctx2.drawImage(game.images[typeJson[this.type].imageName],200,146,55,12,0,0,55,12);
			game.ctx2.restore();
		}else if(this.type =="魔理沙的小激光红"||this.type =="魔理沙的小激光黄" ||this.type =="魔理沙的小激光绿" ||this.type =="魔理沙的小激光蓝" ||this.type =="魔理沙的小激光紫"  ){
			game.ctx2.save();
			game.ctx2.translate(this.x,this.y);
			game.ctx2.rotate(this.direction+Math.PI/2);
			game.ctx2.drawImage(game.images[typeJson[this.type].imageName],typeJson[this.type].px,typeJson[this.type].py,16,14,-8,-250,16,500);
			game.ctx2.restore();
		}else{
			game.ctx2.save();
			game.ctx2.translate(this.x,this.y);
			game.ctx2.rotate(this.direction+Math.PI/2);
			if(this.type == "红星大" || this.type == "蓝星大"|| this.type == "绿星大"|| this.type == "黄星大"|| this.type == "紫星大"||this.type == "绿星小" ||this.type == "黄星小"||this.type=="蓝星小"||this.type=="紫星小"||this.type=="红星小" ){
				game.ctx2.rotate(this.jiaodu);	
			}
			game.ctx2.drawImage(game.images[typeJson[this.type].imageName],typeJson[this.type].px,typeJson[this.type].py,typeJson[this.type].width,typeJson[this.type].height,-typeJson[this.type].width/2,-typeJson[this.type].height/2,typeJson[this.type].width,typeJson[this.type].height);
			game.ctx2.restore();
		}
	};
	Bullet.prototype.update=function(){
		this.x+=this.speed*Math.cos(this.direction);
		this.y+=this.speed*Math.sin(this.direction);
		//小激光扫射激光
		if(this.type =="魔理沙的小激光红"||this.type =="魔理沙的小激光黄" ||this.type =="魔理沙的小激光绿" ||this.type =="魔理沙的小激光蓝" ||this.type =="魔理沙的小激光紫" ){
			this.direction+=this.dj;
			this.x=this.r*Math.cos(this.direction)+this.rx;
			this.y=this.r*Math.sin(this.direction)+this.ry;
			if(Math.abs(this.direction-this.startDirection)>0.52){
				game.deleteEnemyBullet(this);
				return;
			}
		}
		//五角星转圈
		if(this.type == "红星大" || this.type == "蓝星大"|| this.type == "绿星大"|| this.type == "黄星大"|| this.type == "紫星大"||this.type == "绿星小" ||this.type == "黄星小"||this.type=="蓝星小"||this.type=="紫星小"||this.type=="红星小" ){
			this.jiaodu+=this.djiaodu;	
		}
		//
		if(this.type=="player"){
			if(this.y<0){
				game.deletePlayerBullet(this);
			}
		}else{
			if(this.type =="魔理沙的小激光红"||this.type =="魔理沙的小激光黄" ||this.type =="魔理沙的小激光绿" ||this.type =="魔理沙的小激光蓝" ||this.type =="魔理沙的小激光紫"){

			}else{

				if(this.x<-typeJson[this.type].width/2||this.x>game.canvas2.width+typeJson[this.type].width/2||this.y<-typeJson[this.type].height/2||this.y>game.canvas2.height+typeJson[this.type].height/2){
					game.deleteEnemyBullet(this);
				}
			}
		}
		//boom的圆圈 
		if(game.player.isBoom){
			if(Math.abs(this.x-game.player.x)<122 && Math.abs(this.y-game.player.y)<122){
				game.deleteEnemyBullet(this);
			}
		}
		//与自机的判定
		if(game.player.wuDi) return;
		var ds=Math.pow((Math.pow(this.x-game.player.x,2)+Math.pow(this.y-game.player.y,2)),1/2);
		if(typeJson[this.type].pandingXing == "方"){
			var dj=Math.atan2(this.y-game.player.y,this.x-game.player.x);
			var djiao=dj-this.direction;
			if(Math.abs(ds*Math.cos(djiao))<typeJson[this.type].pandingH/2+game.player.pandingR && Math.abs(ds*Math.sin(djiao))<typeJson[this.type].pandingW/2+game.player.pandingR){
				game.player.miss();
				// game.deleteEnemyBullet(this);
				game.player.reStart();
			}
		}else if(typeJson[this.type].pandingXing == "圆"){
			if(ds<game.player.pandingR+typeJson[this.type].pandingR){
				game.player.miss();
				// game.deleteEnemyBullet(this);
				game.player.reStart();
			}
		}

	};

	Bullet.prototype.stop=function(){
		this.speed=0;
	};
	Bullet.prototype.start=function(){
		this.speed=/*game.nanDu**/typeJson[this.type].speed;
	};
})();